name: "zod-debug-test"

services:
  zod-api-debug-test:
    container_name: zod-api-debug-test
    build:
      context: .
      dockerfile: Dockerfile.debug-test
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    env_file:
      - .env
    ports:
      - "8080:${APP_API_PORT:-8080}"
      - "2345:2345"
    networks:
      - zod-network
    working_dir: /app
    volumes:
      - .:/app:cached
    security_opt:
      - "seccomp:unconfined"
    command:
      - "dlv"
      - "test"
      - "./cmd/api"
      - "--headless"
      - "--listen=:2345"
      - "--api-version=2"
      - "--accept-multiclient"

networks:
  zod-network:
    driver: bridge
