FROM golang:1.25-alpine AS builder

WORKDIR /app

RUN go install github.com/go-delve/delve/cmd/dlv@v1.25.2

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -gcflags="all=-N -l" -o /bin/main ./cmd/api

FROM alpine:latest

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

WORKDIR /app

COPY --from=builder /bin/main /bin/main

COPY --from=builder /go/bin/dlv /usr/local/bin/dlv

RUN chown -R appuser:appgroup /app && chown -R appuser:appgroup /bin

USER appuser

EXPOSE 8080
EXPOSE 2345

CMD ["/usr/local/bin/dlv", "exec", "/bin/main", "--headless", "--listen=:2345", "--api-version=2", "--accept-multiclients"]
