FROM golang:1.25-alpine

ARG HOST_UID=1000
ARG HOST_GID=1000
RUN addgroup -g ${HOST_GID} -S appgroup && \
  adduser -u ${HOST_UID} -G appgroup -S -D -h /home/appuser appuser

WORKDIR /app

RUN go install github.com/go-delve/delve/cmd/dlv@v1.25.2

COPY --chown=appuser:appgroup go.mod go.sum ./
RUN go mod download

COPY --chown=appuser:appgroup . .

EXPOSE 8080
EXPOSE 2345

USER appuser

CMD ["/bin/sh"]
